### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by hzoo** [babel/babili#124]
Change it back to `babel-minify`? Ref https://github.com/babel/babili/issues/8

Given that it's just a preset + plugins it makes sense to just be `babel-minify` so everyone understands what it is and we don't have issues trying to explain it or it's pronunciation.

And after talking with people about it (what's that?), I refer to it as the babel minifier anyway. Haven't met many people that liked the name 😛 .

cli: `babili`
preset: `babel-preset-babili`

cli: `babel-minify`
preset: `babel-preset-minify`

---

Message from @thejameskyle:

Since I can already tell this thread will blow up:
# A couple notes before you comment in this thread

Please ensure that any comment you are making on this thread is actively contributing to the discussion of a name change. Please do not go on tangents, please be respectful of others (follow the Babel CoC), and don't just keep repeating something that has been said. Be aware of strawman arguments and other logical fallacies and don't do them. Dont assert your own opinions/experiences as the opinions and experiences of the entire community. Yada yada yada be constructive, be aware, don't be mean.

**Comment by hzoo** [comment]
babili

**Comment by hzoo** [comment]
babili

**Comment by kangax** [comment]
I still like Babili. We can just clarify pronunciation — Babíli vs. Bábel.

**Comment by hzoo** [comment]
don't care

**Comment by amasad** [comment]
Meh... No one what the hell a googol is at first. Stick to your guns, it'll work out

**Comment by amasad** [comment]
Lol, not implying that this will be worth billions of dollars though. Just an example

**Comment by hzoo** [comment]
Haha we can hope

**Comment by thejameskyle** [comment]
I would really prefer renaming it to babel-minify.

We should just have a name that tells people what it is. I don't see a need to hide the meaning behind a name.

**Comment by kangax** [comment]
@thejameskyle I'm not sure why babili is disliked so much. I would really prefer to keep it :) Unique-sounding codenames that don't mean much are pretty common and are usually not a problem — underscore, lodash, angular, ember, cheerio, mocha, gulp, etc.

**Comment by jdalton** [comment]
@kangax
>underscore, lodash, angular, ember, cheerio, mocha, gulp, etc.

[underscore](http://www.dictionary.com/browse/underscore), [angular](http://www.dictionary.com/browse/angular), [ember](http://www.dictionary.com/browse/ember), [mocha](http://www.dictionary.com/browse/mocha), [gulp](http://www.dictionary.com/browse/gulp) are common words and not as search friendly.

Lodash is uniq, it's a play on "low dash", which is an alternative to [underscore](https://en.wikipedia.org/wiki/Underscore). Getting too clever with naming bit Lodash though. It used to be `Lo-Dash` which folks typed as `LoDash`, `lo-dash`, or `Lodash`. I eventually removed the `-` to keep it simple. Something like `babel-minify` gives a pretty clear indication of what it is and avoids communication issues.

**Comment by thejameskyle** [comment]
> Unique-sounding codenames that don't mean much are pretty common and are usually not a problem — underscore, lodash, angular, ember, cheerio, mocha, gulp, etc.

Yeah but almost all of those are all umbrella projects. You then have underscore.string, angular-ui, ember-data, gulp-babel.

Having unique names for each individual thing within the projects just makes it confusing.

**Comment by kangax** [comment]
If everyone finds it confusing then sure, let's change it. I like Babili but I care more about what majority wants :)

**Comment by amasad** [comment]
Let's also rename Babel to AST-Transformer

**Comment by jdalton** [comment]
Babel at least makes a hint of the context and offers a shot at pronunciation (those familiar with the Tower of Babel).

Babili kinda sounds like some odd mashup of Bambi, Pizza rolls, and Italy.

<table>
<tr>
<td align="left">
<img src="https://cloud.githubusercontent.com/assets/4303/18091739/8d4ba804-6e7e-11e6-8e55-278a4017d54f.png" width="100px" height="100px">
</td>
<td> + </td>
<td>
<img src="https://cloud.githubusercontent.com/assets/4303/18091707/7222fa14-6e7e-11e6-80b7-c84e7a9524a0.png" width="100px" height="100px">
</td>
<td> + </td>
<td>
<img src="https://cloud.githubusercontent.com/assets/4303/18092110/e78507b0-6e7f-11e6-9c2c-c08d862768db.png" width="100px" height="100px">
</td>
<td> = Babili </td>
</tr>
</table>

I'm not sure what it is but it's lost any context.

**Comment by brentmclark** [comment]
I vote for Babili.  It's not immediately apparent what it is, sure, but at least you know you've found the droids you were looking for.

**Comment by alavkx** [comment]
Babili is a cooler name for sure, but with the sheer amount of tools developers have to remember to include in their build it only makes sense to name it in a way that describes the use.

**Comment by thejameskyle** [comment]
Since I can already tell this thread will blow up:

# !!!!!!!!!!Note!!!!!!!!!!

Please ensure that any comment you are making on this thread is actively contributing to the discussion of a name change. Please do not go on tangents, please be respectful of others (follow the Babel CoC), and don't just keep repeating something that has been said. Be aware of strawman arguments and other logical fallacies and don't do them. Dont assert your own opinions/experiences as the opinions and experiences of the entire community. Yada yada yada be constructive, be aware, don't be mean.

**Comment by pertrai1** [comment]
babelssor

**Comment by kkemple** [comment]
i prefer the declarative nature of `babel-minify` devs looking in the package json will know immediately what the package does and won't then have to run `npm repo babili` 😜

**Comment by kangax** [comment]
@jdalton Bambi, Pizza rolls, and Italy — are you kidding me?! Is there anything cuter, funner and yummier than this ridiculous, weirdly exciting combo? It's unpossible to not go with that... 🍕 🐴 🇮🇹

**Comment by hzoo** [comment]
I have bab too: https://www.npmjs.com/package/bab

**Comment by pertrai1** [comment]
babelure

**Comment by timdorr** [comment]
If it's supposed to represent something being minified, shouldn't it be `bbl`?

**Comment by hzoo** [comment]
Yeah bbl is great, just don't have the npm name although we could always ask

**Comment by kangax** [comment]
We thought about `bbl` but it's a common abbreviation so would be even more difficult to find/differentiate.

**Comment by gillesdemey** [comment]
As a concerned developer I'd like to mention that it's often refreshing to see a package in my dependencies file that describes what it does instead of having to recall what the hell it was for.

There are so many packages with a "tongue-in-cheek" name that I don't recall what half of them do and I often find myself referring to packages and tools by their description during conversations because I simply can't be bothered to memorize all of them 😞

**Comment by brianc** [comment]
Hey lemme know if you decide to go w/ bbl & it's yours! Much, much, much ❤️ for babel from me! Thanks a million to all the contributors!

**Comment by timdorr** [comment]
> We thought about bbl but it's a common abbreviation so would be even more difficult to find/differentiate.

Big Beautiful Language! 😄 

But yeah, that makes total sense. Just suggesting it so there's an option. I think I'd prefer babel-minify personally.

**Comment by MatthiasWinkelmann** [comment]
I'd like to quickly make the vain attempt to argue for poetry in world of prose: An evocative name can, sometimes, bring a moment of levity, a hint of a smile in an otherwise dull day. It can help the project if it adds emotion to function, if only by being more easy to remember (which also helps users). My favorite example is "Plan B" for the morning-after pill. [This naming agency](https://www.igorinternational.com/process/evocative-product-company-names.php) (no connection) has a bunch of articles on it.

I'm on the fence if it makes sense here, and I'd say only "bbl" actually fits the idea. It's mostly a matter of size: a programming language can afford to have a non-descriptive name, leftpad should rebrand to 000001.js, but a project that isn't at the center of attention may just make life difficult for everyone by trying to be clever. Does a minifier have the mindshare it takes? I'd say "yes, but it's close".

Because I've frequently run into the what-does-this-package-do-again-problem cited above, I'd also like the following snippet. Maybe it should be used more often in install instructions to make it common practice?

```
"bbl": "minifier using the babel toolchain",
"bbl": "^1.0.0"
```

**Comment by johanssj** [comment]
Whilst I myself upvoted 'babel-minify' earlier on in this thread, Matthias has some really powerful arguments here that I emphasise with. 000001.js is a no brainer in hindsight. (Brilliant Matthias. Is that your own original idea?) Likewise in hindsight, 'bbl' needs a second look.

Also, being a long time C/C++ veteran, accustomed to typing 'cc', I think I could easily get rather comfortable and cosy typing 'bb' when using a tool such as Babel which is rapidly becoming ubiquitous in the ECMAScript universe. Maybe in not so long time, Babel + the (its) minifier will be thought of one and the same, like a holy duo. Just an idea, perhaps the Bavel CLI itself could be envoked with just 'bb' and something like a '-m' option to invoke the minifier?  Notice that another variant, 'bl', which is yet a further contraction of 'babel', is a play on 'cl' which some C/C++ compiler CLI's use.

**Comment by timoxley** [comment]
*leaves bikeshed*

**Comment by timoxley** [comment]
The fanciness of the name should roughly reflect the level of attention required of the developer. Since a precise, self-explanatory name is available and **this is just a minifier**, having a fancy name seems like unnecessary obfuscation, regardless how clever it is.

**Comment by chicoxyzzy** [comment]
Can the CLI be named Babili and use babel-minify/babel-preset-minificatio under the hood?

**Comment by hzoo** [comment]
The name change would really only be for the preset/cli name. All the plugins are independent. We can always alias as well

**Comment by kangax** [comment]
What I like about "Babili" is that it gives project identity. 

We can change the name to something more common and easier to pronounce but I really wish it wouldn't just be "babel-minify". That sounds boring, generic, repetitive/longer to pronounce (if you're talking to someone or giving a talk). It makes more sense for me to hear/say "Meet Babili, a Babel-based minifier" vs. "Meet babel-minify, a babel-based minifier" (what a nice tongue twister). 

You can argue that "babel-minify" speaks for itself and then you don't really need to even explain it. But then it's still awkward — if "babel-minify" is a minifier then why isn't it "babel-minifier" or just "Babel Minifier". Is it something that minifies babel (as "babel-minify" would suggest?).

Codenames are good because they're memorable, recognizable, easier to reference. Even the ones that make no sense could work — anyone wondered what in the world "yeoman" is when it came out? We can get the best of both worlds by coming up with something relevant (aka uglify), yet unique. But please let's not do "babel-minify".

/end of bikeshed

**Comment by nikolay** [comment]
@kangax You like the name - fine! Use it for some other project. But you don't need multiple brands for some little utility within Babel. From a marketing point of view, having more brands is worse than less ones. Focus on Babel and build on top of it - babel-min, if you wish, but don't ruin the main brand!

**Comment by alexeyraspopov** [comment]
As a +1 for project identity argument, here is another one.

Not everyone uses Babel for their projects. In the future™ we all hope to not use Babel because we'll be able to write just modern JavaScript that does not require compilation step. However, we still need minifiers for a production environment. That's where Babili (as separate, recognizable project) steps in. While Uglify's maintainers are [working](https://github.com/mishoo/UglifyJS2/issues/448) on ES6+ support, Babili can do it by default.

**Comment by kangax** [comment]
@nikolay Why do you think it's a "little utility within Babel"? The minifier is a standalone tool on top Babel/Babylon. It's no smaller or different than, say, ESLint which is based on Esprima. I don't see how Babel is affected (ruined) by this at all.

**Comment by TomYeoman** [comment]
My vote is for babel-minify, I've been waiting for it for ages and yet when I read your post on HN about it I had no clue it was just a minifier until I stumbled upon a link to this issue reading through the comments!

**Comment by nikolay** [comment]
@alexeyraspopov So, your logic is: Keep a non-Babel-related name so people who don't like Babel could be stupid enough to use this instead of Uglify.

Don't get too emotionally attached to things that don't really matter!

In fact, if this is detached from the Babel's brand, being loyal to Babel will keep us using this as part of the ecosystem. Don't try to steal Uglify's "customers" - try to keep us instead.

You created a poll of sorts and a lot of people voted. But, yes, you have all the rights to ignore the feedback.

**Comment by MatthiasWinkelmann** [comment]
A developer spends orders of magnitude more time seeing the name, creating folders with that name, seeing their name in the same sentence as the project's name or giving presentations on <name>.

The user's interests are best served by keeping those guys/gals happy, especially regarding such subjective issues.

Personally, I'd argue that "naming your baby" is a sort of natural right of a creator, but I see how that's somewhat subjective.

So to those putting in the hard work: do what you're comfortable with; this project will be measured with yardsticks other than its name. And don't feel bound by on online poll – creative endeavors aren;t usually a good fit for "wisdom of the crowds".

**Comment by mstade** [comment]
This mostly seems like bike shedding to me (so naturally I'll jump in) and probably doesn't matter much in the end. `Babili` is a fine name, so would probably most *any* other name be. Arguments that `babel-minify` would more accurately describe what the preset does is not entirely on point, since `minifying` is just the JS community's own term for `optimizing`. Following that logic, you may as well call it `babel-optimize` or something to that effect. My point being: for all consumer's sake it's probably less important what the thing is called, and more important that it does what it says on the tin.

**Comment by jdalton** [comment]
I just did a search for babel-minify because I had forgotten this name.

**Comment by mikesherov** [comment]
I vote `babel-minify`, especially for the preset name. Here's my .babelrc... one of these things is not like the other:

```
presets: [
  "es2015",
  "stage-3",
  "babili"
]
```

If we want to resolve this incongruence, we can either: rename this to "minify", so the list of presets clearly express what they do. Or, rename all the other presets to "branded" terms like "TwonOneFive" and "StableTown" for es2015 and stage-3 respectively.

**Comment by fnlctrl** [comment]
+1 for `bab` over `babili`/`bbl`, because it matches its purpose (minifing things, including names), it hints people that it's related `babel`, it's easy to read/pronounce/remember,  and it's cool.  `bbl` is hard to read because of dropped vowels, and it hardly makes people think of `babel` at first glance.

Though `babel-minify` should be the necessary one.

**Comment by superherointj** [comment]
For our own sanity, rename this to "minify"!

**Comment by scottohara** [comment]
I only recently discovered `babili` after removing my `babel` build step (now that all desktop/mobile browsers have near complete ES2015 support, and I'm not using any ES2016+ yet), only to discover that `uglify` doesn't support arrow functions (!?).

The very next day I wanted to read more about it, but promptly forgot if it was spelled `babili`, `babeli`, `babilli`, `babelli`, etc.

I took a (wrong) guess at `babeli` (on the assumption that it was `babel` + `i`) and found nothing on the first page of Google results.

I ended up googling "babel minifier" to find it.

So on that basis, I would personally vote for `babel-minify`.

**Comment by nikolay** [comment]
@scottohara Yup! Without any doubt, "uglify" is a more **beautiful** name tan "babili"!

**Comment by chicoxyzzy** [comment]
I can't imagine how browserify people will call babili transformer. Babiliify? 🤔

**Comment by pertrai1** [comment]
Take a look at the names of the tv characters for Transformers and give the name its own identity that people can relate to: https://www.wikiwand.com/en/List_of_The_Transformers_(TV_series)_characters

**Comment by patrickjuchli** [comment]
I like Babili because the suffix `-li` is used as a diminutive in Swiss German.

It's used to make things small and cute. That's where the names for Google's new compression algorithms come as well. `Brotli` (should actually be Brötli) means small piece of bread, `Brot` being the actual word for bread. Same thing with `Zopfli` (Zöpfli), another type of bread called `Zopf`. Lately they added Guetzli, a new JPEG encoder and the word for cookie. Cookies are always small and cute so I'm not aware of the non-cute version. An in all a very Swiss thing, see my name.

**Comment by hzoo** [comment]
Ok well I didn't take that long to decide.. not

I wanted to change it to `babel-minify` for a while and I don't think anyone on the team disagrees? It's clearly voted on 10x more, and makes more sense for anyone that is newer (babel-minify makes sense) and theres way too many changes people ask "what's that babel minify thing called".

The individual packages don't reference babili, so we'll just have to update the main pkg + integrations (webpack, rollup, cli, gulp, etc), and docs.
