### ISSUE TITLE
Incorrect function name for methods

### ISSUE THREAD

**Issue by jfsiii** [babel/babili#131]
As you can [see in the REPL](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015&experimental=false&loose=false&spec=false&code=function%20foo%28%29%20%7B%0A%20%20function%20getX%28o%29%7B%20return%20o.x%3B%20%7D%0A%20%20const%20obj%20%3D%20%7B%0A%20%20%20%20getter%3A%20getX%0A%20%20%7D%3B%0A%20%20return%20obj%0A%7D%0A&playground=false)

``` js
function foo() {
  function getX(o){ return o.x; }
  const obj = {
    getter: getX
  };
  return obj
}
```

is transformed to

``` js
"use strict";function foo(){return{getter:function getter(b){return b.x}}}
```

The returned function should retain its original name (`getX` in this case) not take on the name of the property (`getter` here).

This [appears to work as expected](http://babeljs.io/repl/#?babili=true&evaluate=true&lineWrap=false&presets=es2015&experimental=false&loose=false&spec=false&code=function%20getX%28o%29%7B%20return%20o.x%3B%20%7D%0Aconst%20obj%20%3D%20%7B%0A%20%20getter%3A%20getX%0A%7D%3B&playground=false) outside of a function.

**Comment by boopathi** [comment]
Weird why it gets a function name in the first place. On the latest master though the function name `getter` is not available and is the expected behaviour -as it is not used/referenced anywhere as far as the minifier can tell -

So, we have an option to bail out of this - [`keepFnames`](https://github.com/babel/babili/tree/master/packages/babel-plugin-minify-dead-code-elimination#options). We will enable these options to be passed in from the preset directly in future - you can track that here - #54

**Comment by hzoo** [comment]
It depends on what presets you use - there is a es2015 transform that adds the name, if you use a different preset (say react) it won't be there I think

**Comment by boopathi** [comment]
No longer an issue. Can use `keepFnName` - and it retains the fn name as `getX`
