### ISSUE TITLE
`arguments` incorrectly mangled

### ISSUE THREAD

**Issue by kangax** [babel/babili#191]
```js
(function() {
  var arguments = undefined;
  (function () { 
    alert(arguments.length === 0);
  })();
 })();
```

is incorrectly mangled to:

```js
(function() {
  var a = void 0;
  (function () {
    alert(a.length === 0);
  })();
})();
```

`arguments` shouldn't be mangled.

**Comment by boopathi** [comment]
is there anything else to be added to the ignore list like `arguments` ?

**Comment by kangax** [comment]
Doesn't Babel have a method to check if a name is suitable for an identifer?

**Comment by boopathi** [comment]
I'm not sure. there is `t.isValidIdentifier`, but I don't know anything of this sort.

**Comment by kangax** [comment]
Right, so shouldn't that disallow `arguments`, in which case we can't mangle it?

**Comment by loganfsmyth** [comment]
The issue is that `arguments` isn't a keyword, it's just a binding identifier that has standardized behavior and that is disallowed as a variable name in strict code. We'll have to exclude it manually.

Looking at the spec, I think if it's declared with `let` in non-strict code, we can mangle it technically, but it's probably not worth that complexity.
