### ISSUE TITLE
Possible to change the mangle name blacklist while using babili preset?

### ISSUE THREAD

**Issue by gauntface** [babel/babili#279]
At the moment I'm trying to prevent a class name 'ExampleError' from getting mangled by Babili, I'm doing:

    .pipe(babel({
      presets: ['babili', {
        comments: false,
        plugins: [{'minify-mangle-names': {blacklist: {'ExampleError': true}}}],
      }],
    }))

I've tried other variants but I'm just not getting anywhere, only receiving the error:

    Error: Plugin 0 specified in "foreign" provided an invalid property of "minify-mangle-names"

Any help would be greatly appreciated.

Matt

**Comment by boopathi** [comment]
Unfortunately it's not possible now with preset. Preset options are going to land soon - #162. 

For now, you can copy the list of plugins from the preset index.js and apply mangle properties to the mangle plugin.

If you use the preset as well as the mangler separately in your plugin list, you ll end up mangling that blacklist anyway because it will be applied twice.

**Comment by gauntface** [comment]
Thanks for the info. I'll just give up on what I was trying to do and maybe come back round to this at a later date.

**Comment by boopathi** [comment]
Preset options are now supported. https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options
