### ISSUE TITLE
Strict inequality (!==) transformed into inequality (!=)

### ISSUE THREAD

**Issue by noodle71** [babel/babili#323]
Hello,

First of all, thank you for your amazing work.

I've found a bug using JQuery and Babili. When you minify JQuery, using the $.extend method, we get wrong results.

It's because of this comparison:

https://github.com/jquery/jquery/blob/master/src/core.js#L189

The code is transformed into this:

```js
me.extend = me.fn.extend = function() {
            var Zt, en, tn, nn, an, on, sn = arguments[0] || {}, rn = 1, ln = arguments.length, dn = !1;
            for ("boolean" == typeof sn && (dn = sn,
            sn = arguments[rn] || {},
            rn++),
            "object" == typeof sn || me.isFunction(sn) || (sn = {}),
            rn === ln && (sn = this,
            rn--); rn < ln; rn++)
                if (null != (Zt = arguments[rn]))
                    for (en in Zt)
                        (tn = sn[en],
                        nn = Zt[en],
                        sn !== nn) && (dn && nn && (me.isPlainObject(nn) || (an = me.isArray(nn))) ? (an ? (an = !1,
                        on = tn && me.isArray(tn) ? tn : []) : on = tn && me.isPlainObject(tn) ? tn : {},
                        sn[en] = me.extend(dn, on, nn)) : void 0 != nn && (sn[en] = nn));
            return sn
        }
```

The comparison "void 0 != nn" is not the same as "copy !== undefined" because **nn** could be null and according to JQuery code documentation they just ignore undefined not null values:

```js
// Don't bring in undefined values
} else if ( copy !== undefined ) {
  target[ name ] = copy;
}
```

Best regards,

**Comment by boopathi** [comment]
This is done by simplify-comparison-operators. from next version of babili you should be able to disable that plugin through babili options - https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options

**Comment by kangax** [comment]
Our plugin says that we only change operator if operands' types are inferred to be the same. So this looks like a bug to me — we shouldn't be changing operator in this case.

**Comment by kangax** [comment]
@boopathi check out this weirdness. I reduced it to a minimal test case:

```js
!function() {
  var x, y;
  y = o[x];
  foo(y !== undefined);
}();```

This transforms `!==` to `!=`.

Curiously, doing `y = blah` doesn't have this issue. Neither does `y = o[blah]`. Something about this specific use of local vars (?) makes it think that `y` is still `undefined` or something like this. I'll dig more.

**Comment by kangax** [comment]
Interesting...

This only happens when **both** "transform-simplify-comparison-operators" and "minify-simplify" are used.

And it's probably because it transforms to a sequence expression so it doesn't "know" about assignment:

```js
b=o[a],foo(b!=void 0)
```

**Comment by kangax** [comment]
So... it thinks that `left.baseTypeStrictlyMatches(right)` is `true` because `y`'s type resolves to `VoidTypeAnnotation` vs. `AnyTypeAnnotation`. Something in simplify messes up the type of `y`.

Also, replacing `y = o[blah]; foo(y !== undefined)` with `y = o[blah], foo(y !== undefined)` fixes the problem, since simplify plugin no longer needs to transform statements into a sequence of expressions.

Digging more.

**Comment by kangax** [comment]
Something in `toMultipleSequenceExpressions` makes nodes have incorrect type information. In this case, `y`'s type is "VoidTypeAnnotation" instead of "AnyTypeAnnotation". I'm not sure where in Babel types are set, but I'll see if I can find anything in that helper.

**Comment by kangax** [comment]
Omg, this is so bizarre.

I was debugging minify-simplify and narrowed it to `BlockStatement` visitor which calls `toMultipleSequenceExpressions` and replaces `node.body` with them.

The crazy part is that for inspection I used

```js
path.traverse({
  BinaryExpression: function(path) {
    path.get('left').getTypeAnnotation();
  }
});
```
.. from within `BlockStatement` visitor. And as soon as I did that, problem disappeared. LVal started being reported as having "AnyTypeAnnotation" instead of incorrect "VoidTypeAnnotation".

More generically, if we just do this for all identifiers from within:

```js
path.traverse({
  Identifier: function(path) {
    path.getTypeAnnotation();
  }
});
```

it still works. I have no idea why and how it all works underneath though.
