### ISSUE TITLE
Identifier {X} has already been declared

### ISSUE THREAD

**Issue by Samlv9** [babel/babili#365]
when i using `babili@0.0.9` to compile this code:
```javascript
(function(){
    try { eval("class __{};"); }
    catch(e) { return null; }
    
    class A { static ABC = 10; };
    class B { static DEF = 20; };
    
    window.C = A.ABC;
    window.D = B.DEF;

    console.log(A, B);
}());
```
i get this result:
```javascript 
(function(){try{eval("class __{};")}catch(a){return null}class a{}a.ABC=10;class a{}a.DEF=20;window.C=a.ABC,window.D=a.DEF,console.log(a,a
)})();
```

**there is two definition of variable 'a'**, when i try using `node@6.0` to run the result, i have get an error like:
```shell
SyntaxError: Identifier 'a' has already been declared
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
``` 

But, if i remove the `try...catch` statement, it have product the correct result. i wanna use `try...catch` because if the browser does support es6 classes, then exits run this code, how can i do this ?

**Comment by kangax** [comment]
I thought Babel doesn't work with eval?

**Comment by boopathi** [comment]
This is happening because ClassDeclarations have bindings in two scopes where as FunctionDeclarations have bindings only in the scope where it is defined. I have faced this problem in mangler sometime back, but some rewrite fixed it.

Example: http://astexplorer.net/#/VstAUrU0JT Here, you can see class `A` binding appears in the scope where the class is declared and class's own scope. FunctionDeclaration `B` is registered only in the scope where the function is declared. 

Not sure whether this is a bug in babel. Also, not sure what else this might break in other plugins.
